name: Branch Protection Rules

on:
  # This workflow runs when it's manually triggered
  workflow_dispatch:
  # It also runs on schedule, once a day
  schedule:
    - cron: '0 0 * * *'

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Get default branch
            const { data: repository } = await github.rest.repos.get({
              owner,
              repo
            });
            
            const defaultBranch = repository.default_branch;
            
            // Set branch protection rules
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: defaultBranch,
              required_status_checks: {
                strict: true,
                contexts: ['CI', 'SCA']  // These must match the job names in your workflows
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null
            });
            
            console.log(`Branch protection rules set for ${defaultBranch}`);