name: CI

on: [push, workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: SAST - Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./" -e="false"
          # Run horusec and generate the report.
          horusec start -p="./" -e="false" --output-format sarif --json-output-file sast-horusec-report.sarif ./
          horusec start -p="./" -e="false" --output-format json --json-output-file sast-horusec-report.json ./
          horusec start -p="./" -e="false" --output-format text --json-output-file sast-horusec-report.txt ./
      
      - name: SAST - Horusec Reports Attachment
        uses: actions/upload-artifact@v4
        with:
          name: horusec-reports
          path: |
            sast-horusec-report.*

      - name: SAST - NJSScan
        run: |
          pip install njsscan
          # Generate Report in JSON.
          njsscan --json -o njsscan-report.json .
          # Generate Report in SARIF.
          njsscan --sarif -o njsscan-report.sarif .
          # Just cat the report to the console.
          cat njsscan-report.json

      - name: SCA Dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          skip-dirs: ./test

      - name: SCA IAC
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          skip-dirs: ./test

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build Artefacts
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            brunobotelhobr/my-sample-api:${{ github.run_number }}
            brunobotelhobr/my-sample-api:latest

      - name: SCA Artefacts
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'brunobotelhobr/my-sample-api:latest'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'