# This workflow runs Dependabot and checks for dependency errors on push and pull request events
name: Dependabot & Dependency Check

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main
      - "*"

jobs:
  dependabot:
    name: Run Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  dependency-check:
    name: Dependency Error Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install --ignore-scripts;
          fi
      - name: Check for dependency errors
        run: |
          if [ -f package.json ]; then
            npm audit --audit-level=high || exit 1;
          fi
