on: [push, pull_request, workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Download Code
        uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build Artefacts
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            brunobotelhobr/api_conversao:${{ github.run_number }}
            brunobotelhobr/api_conversao:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Download Code
        uses: actions/checkout@v2

      - name: Okteto Get Kubeconfig
        uses: okteto/namespace@latest
        id: namespace
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: brunobotelhobr

      - name: Okteto Deploy and Wait
        uses: okteto/deploy-stack@latest
        with:
          namespace: brunobotelhobr
          file: k8s/deployment.yml

  QA:
    needs: [CD]
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v2

      - name: Sleep for 45s
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s

      - name: QA tests
        run: chmod +x test/qa.sh; test/qa.sh
