name: Security-SCA-Push

on:
  push:
    branches-ignore:
      - main
    
  workflow_call:
  workflow_dispatch:

jobs:
  SCA-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          
          base-ref: ${{ github.event.before || github.sha }}
          head-ref: ${{ github.sha }}