name: Security-SCA-PR

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          license-check: true