# Dependabot configuration for security and SCA (Software Composition Analysis)
# This workflow uses GitHub's official "dependency-review-action" and is highly configurable.

name: Security-SCA

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write  # Needed to upload SARIF results

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Defines the threshold for the level of severity. The action will fail on any pull requests that introduce vulnerabilities of the specified severity level or higher.
          fail-on-severity: medium

          # Enable or disable the license check performed by the action.
          license-check: true

          # Enable or disable the vulnerability check performed by the action.
          vulnerability-check: true

          # Provide custom git references for the git base/head when performing the comparison check. Only used for event types other than pull_request and pull_request_target.
          base-ref: ${{ github.event.before || github.sha }}
          head-ref: ${{ github.sha }}

          # Enable or disable reporting the review summary as a comment in the pull request. Possible values: always, on-failure, never
          comment-summary-in-pr: always

      # Upload SARIF results to GitHub Security tab
      - name: Upload SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sast-horusec-report.sarif
          category: horusec

      - name: Upload NJSScan SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sast-njsscan-report.sarif
          category: njsscan

      - name: Upload Trivy SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sca-trivy.sarif
          category: trivy-fs

      - name: Upload IAC Trivy SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: iac-scan-trivy.sarif
          category: trivy-iac

      - name: Upload Image Trivy SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sca-trivy-image.sarif
          category: trivy-image